export interface CollectionsModel {

    OVERHAULS_COLLECTION: string
    LABELS_COLLECTION: string;
    LABELS_IMPORT_COLLECTION: string;
    LABELS_LOCK_COLLECTION: string;
    LABELS_BACKUP_COLLECTION: string;
    AUDIT_EVENTS_COLLECTION: string;
    COUNTRIES_COLLECTION: string;
    PROVIDERS_COLLECTION: string;
    RESSOURCES_COLLECTION: string;
    APPLICATION_STATES_COLLECTION: string;
    APPLICATIONS_STATUS_COLLECTION: string;
    APPLICATIONS_ACCESS_COLLECTION: string;

}
